spring:
  datasource:
    url: jdbc:mysql://{DB_USER}:{DB_PWD}/{DB_NAME}}?serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: zz126578
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
